// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"
	"time"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, room_id, sender_id, content, created_at)
VALUES (?, ?, ?, ?, COALESCE(?, CURRENT_TIMESTAMP))
`

type CreateMessageParams struct {
	ID       string      `json:"id"`
	RoomID   string      `json:"room_id"`
	SenderID string      `json:"sender_id"`
	Content  string      `json:"content"`
	Column5  interface{} `json:"column_5"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.RoomID,
		arg.SenderID,
		arg.Content,
		arg.Column5,
	)
	return err
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT m.id, m.room_id, m.sender_id, u.username AS sender_name, u.avatar_url AS sender_avatar_url, m.content, m.attachment_url, m.attachment_type, m.created_at
FROM messages m
JOIN users u ON m.sender_id = u.id
WHERE m.room_id = ?
ORDER BY m.created_at ASC
LIMIT ? OFFSET ?
`

type ListMessagesByRoomParams struct {
	RoomID string `json:"room_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListMessagesByRoomRow struct {
	ID              string    `json:"id"`
	RoomID          string    `json:"room_id"`
	SenderID        string    `json:"sender_id"`
	SenderName      string    `json:"sender_name"`
	SenderAvatarUrl string    `json:"sender_avatar_url"`
	Content         string    `json:"content"`
	AttachmentUrl   string    `json:"attachment_url"`
	AttachmentType  string    `json:"attachment_type"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]ListMessagesByRoomRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByRoom, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByRoomRow
	for rows.Next() {
		var i ListMessagesByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.SenderName,
			&i.SenderAvatarUrl,
			&i.Content,
			&i.AttachmentUrl,
			&i.AttachmentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
