ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT DEFAULT '' NOT NULL;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS attachment_url TEXT DEFAULT '' NOT NULL;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS attachment_type TEXT DEFAULT '' NOT NULL;
