// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, room_id, sender_id, content, created_at)
VALUES ($1, $2, $3, $4, COALESCE($5, CURRENT_TIMESTAMP))
RETURNING id, room_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	ID        uuid.UUID   `json:"id"`
	RoomID    uuid.UUID   `json:"room_id"`
	SenderID  uuid.UUID   `json:"sender_id"`
	Content   string      `json:"content"`
	CreatedAt interface{} `json:"created_at"`
}

type CreateMessageRow struct {
	ID        uuid.UUID          `json:"id"`
	RoomID    uuid.UUID          `json:"room_id"`
	SenderID  uuid.UUID          `json:"sender_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.RoomID,
		arg.SenderID,
		arg.Content,
		arg.CreatedAt,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT m.id, m.room_id, m.sender_id, u.username AS sender_name, u.avatar_url AS sender_avatar_url, m.content, m.attachment_url, m.attachment_type, m.created_at
FROM messages m
JOIN users u ON m.sender_id = u.id
WHERE m.room_id = $1
ORDER BY m.created_at ASC
LIMIT $2 OFFSET $3
`

type ListMessagesByRoomParams struct {
	RoomID uuid.UUID `json:"room_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListMessagesByRoomRow struct {
	ID              uuid.UUID          `json:"id"`
	RoomID          uuid.UUID          `json:"room_id"`
	SenderID        uuid.UUID          `json:"sender_id"`
	SenderName      string             `json:"sender_name"`
	SenderAvatarUrl string             `json:"sender_avatar_url"`
	Content         string             `json:"content"`
	AttachmentUrl   string             `json:"attachment_url"`
	AttachmentType  string             `json:"attachment_type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]ListMessagesByRoomRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByRoom, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByRoomRow
	for rows.Next() {
		var i ListMessagesByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.SenderName,
			&i.SenderAvatarUrl,
			&i.Content,
			&i.AttachmentUrl,
			&i.AttachmentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
