// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (id, name, type, created_at)
VALUES ($1, $2, $3, COALESCE($4, CURRENT_TIMESTAMP))
RETURNING id, name, type, created_at
`

type CreateRoomParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	CreatedAt interface{} `json:"created_at"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.CreatedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const createRoomMember = `-- name: CreateRoomMember :exec
INSERT INTO room_members (room_id, user_id, joined_at)
VALUES ($1, $2, COALESCE($3, CURRENT_TIMESTAMP))
`

type CreateRoomMemberParams struct {
	RoomID   uuid.UUID   `json:"room_id"`
	UserID   uuid.UUID   `json:"user_id"`
	JoinedAt interface{} `json:"joined_at"`
}

func (q *Queries) CreateRoomMember(ctx context.Context, arg CreateRoomMemberParams) error {
	_, err := q.db.Exec(ctx, createRoomMember, arg.RoomID, arg.UserID, arg.JoinedAt)
	return err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, type, created_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomMembers = `-- name: GetRoomMembers :many
SELECT u.id, u.username, u.email, rm.joined_at
FROM room_members rm
JOIN users u ON rm.user_id = u.id
WHERE rm.room_id = $1
ORDER BY u.username ASC
`

type GetRoomMembersRow struct {
	ID       uuid.UUID          `json:"id"`
	Username string             `json:"username"`
	Email    string             `json:"email"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetRoomMembers(ctx context.Context, roomID uuid.UUID) ([]GetRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, getRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomMembersRow
	for rows.Next() {
		var i GetRoomMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, type, created_at
FROM rooms
ORDER BY created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
