// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        uuid.UUID          `json:"id"`
	RoomID    uuid.UUID          `json:"room_id"`
	SenderID  uuid.UUID          `json:"sender_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RoomMember struct {
	RoomID   uuid.UUID          `json:"room_id"`
	UserID   uuid.UUID          `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
