// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateRoomMember(ctx context.Context, arg CreateRoomMemberParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error)
	GetRoomMembers(ctx context.Context, roomID uuid.UUID) ([]GetRoomMembersRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]ListMessagesByRoomRow, error)
	ListRooms(ctx context.Context) ([]Room, error)
}

var _ Querier = (*Queries)(nil)
